#pragma once
//
// Created by giuseppe on 08/11/20.
//


#define LOGINSNC "LOGINSNC"
#define USERNAME "USERNAME"
#define PASSWORD "PASSWORD"
#define REQRTREE "REQRTREE"
#define FILEHASH "FILEHASH"
#define FILEPATH "FILEPATH"
#define POSTFILE "POSTFILE"
#define FILEDATA "FILEDATA"
#define REMVFILE "REMVFILE"
#define STOPFLOW "STOPFLOW"
#define __RESULT "__RESULT"
#define REQRFILE "REQRFILE"
#define SIGNUPNU "SIGNUPNU"
